const products = [
  {
    _id: '1',
    name: 'Kashmiri Design Carpet',
    image: '/images/carpet-01.jpg',
    description: 'Kashmiri Design Royal Look Persian Carpet for Your Hall & Living Room with 1 inch Thickness 5 X 7 Feet (150x210 cm) Multi',
    brand: 'Apple',
    category: 'Carpets',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Handmade Tuffted Woollen Carpet',
    image: '/images/carpet-02.jpg',
    description: 'Handmade Tuffted Woollen Thick Geometrical Carpet 6 x 9 feet (180X270 cm)',
    brand: 'Homestyle',
    category: 'Carpets',
    price: 99.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Velvet Touch Carpet',
    image: '/images/carpet-03.jpg',
    description: 'Velvet Touch Bedroom, Hall, Living Room, Drowing Room Abstract Chenille Carpet - |60" inch x 84" inch | 5 Feet x 7 Feet | Blue',
    brand: 'Homestyle',
    category: 'Carpets',
    price: 900.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Handmade Jute Rug',
    image: '/images/carpet-04.jpg',
    description: 'Handwoven Jute Rug, Natural Fibres, Braided Reversible Carpet for Bedroom Living Room Dining Room (ROUND16, 70 cm)',
    brand: 'Homestyle',
    category: 'Carpets',
    price: 99.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '5',
    name: 'Kashmiri Design Carpet',
    image: '/images/carpet-01.jpg',
    description: 'Kashmiri Design Royal Look Persian Carpet for Your Hall & Living Room with 1 inch Thickness 5 X 7 Feet (150x210 cm) Multi',
    brand: 'Apple',
    category: 'Carpets',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Velvet Touch Carpet',
    image: '/images/carpet-03.jpg',
    description: 'Velvet Touch Bedroom, Hall, Living Room, Drowing Room Abstract Chenille Carpet - |60" inch x 84" inch | 5 Feet x 7 Feet | Blue',
    brand: 'Homestyle',
    category: 'Carpets',
    price: 900.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
]

export default products
